<?php require "auth.php"; $u=$pdo->prepare("SELECT * FROM users WHERE id=?");$u->execute([$me]);$meu=$u->fetch();
$ageExpr="TIMESTAMPDIFF(YEAR,dob,CURDATE())";
// Only show users from the same city as the current user (case-insensitive)
$s=$pdo->prepare("SELECT *, $ageExpr age FROM users WHERE id<>? AND gender=? AND interested_in=? AND LOWER(location)=LOWER(?) ORDER BY created_at DESC");
$s->execute([$me, $meu['gender'], $meu['interested_in'], $meu['location']]);
$profiles=$s->fetchAll();
$matches=$pdo->prepare("SELECT u.* FROM users u JOIN likes l ON l.liked_id=u.id JOIN likes r ON r.liker_id=u.id AND r.liked_id=l.liker_id WHERE l.liker_id=?");$matches->execute([$me]);$matchList=$matches->fetchAll(); 
$adminEmail = "hopenambuta@gmail.com";
$isAdmin = ($meu['email'] === $adminEmail);
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Discover</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body><nav class="navbar bg-white"><div class="container"><b class="text-danger">♥ HeartLink</b><div><span class="me-3">Hi, <?=htmlspecialchars($meu["name"])?></span><?php if($isAdmin):?><a href="admin_payments.php" class="btn btn-warning btn-sm me-2">Admin Payments</a><?php endif;?><a href="logout.php" class="btn btn-outline-secondary btn-sm">Logout</a></div></div></nav><main class="container py-4"><h2>Discover</h2><div class="row g-4"><?php foreach($profiles as $p):?><div class="col-md-4"><div class="card"><?php if($p["photo"]):?><img class="avatar" src="<?=htmlspecialchars($p["photo"])?>"><?php else:?><div class="avatar d-flex align-items-center justify-content-center bg-light display-1">♥</div><?php endif;?><div class="p-3"><h4><?=htmlspecialchars($p["name"])?> <small class="text-muted"><?=$p["age"]?></small></h4><p><?=htmlspecialchars($p["location"])?></p><p><?=nl2br(htmlspecialchars($p["bio"]))?></p><a class="btn btn-love" href="like.php?id=<?=$p["id"]?>">♥ Like</a> <a class="btn btn-outline-secondary" href="message.php?id=<?=$p["id"]?>">Message</a></div></div></div><?php endforeach;if(!$profiles):?><p>No matching profiles yet.</p><?php endif;?></div><hr><h3>Your Matches</h3><div class="list-group"><?php foreach($matchList as $m):?><a class="list-group-item list-group-item-action" href="message.php?id=<?=$m["id"]?>">♥ <?=htmlspecialchars($m["name"])?></a><?php endforeach;if(!$matchList):?><p>No mutual matches yet.</p><?php endif;?></div></main></body></html>