CREATE DATABASE IF NOT EXISTS dating_site CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dating_site;
CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(190) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL, gender ENUM('male','female') NOT NULL,
 interested_in ENUM('male','female') NOT NULL, dob DATE NOT NULL, location VARCHAR(100) DEFAULT '',
 bio TEXT, photo VARCHAR(255) DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE likes (id INT AUTO_INCREMENT PRIMARY KEY, liker_id INT NOT NULL, liked_id INT NOT NULL,
 UNIQUE KEY uq_like(liker_id,liked_id), FOREIGN KEY(liker_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(liked_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, sender_id INT NOT NULL, receiver_id INT NOT NULL,
 message TEXT NOT NULL, is_read TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE reports (id INT AUTO_INCREMENT PRIMARY KEY, reporter_id INT NOT NULL, reported_id INT NOT NULL,
 reason TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
